# Generated by Django 4.2.4 on 2023-08-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('PhoneNumber', models.CharField(blank=True, max_length=20)),
                ('Code', models.CharField(blank=True, max_length=6, null=True)),
                ('ReferralCode', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
