# Generated by Django 4.2.4 on 2023-08-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralmodel',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='referralmodel',
            name='ReferralCode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
